#!/bin/sh

set -e

umask 0022
ACTION="$1"
VERSION="$2"

if [ "$ACTION" = "configure" ]; then
    # add the mpd user
    if ! getent passwd mpd >/dev/null; then
        adduser --quiet --ingroup audio --system --no-create-home \
            --home /var/lib/mpd mpd
    fi

    # set ownership and permissions on directories
    for i in /var/log/mpd /var/lib/mpd /var/lib/mpd/playlists; do
        if ! dpkg-statoverride --list --quiet "$i" >/dev/null; then
            dpkg-statoverride --force --quiet --update \
                --add mpd audio 0755 "$i"
        fi
    done

    # set ownership and permissions on mpd.conf
    if ! dpkg-statoverride --list --quiet /etc/mpd.conf >/dev/null; then
        dpkg-statoverride --force --quiet --update \
            --add mpd audio 0640 /etc/mpd.conf
    fi
fi

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask mpd.socket >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled mpd.socket; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable mpd.socket >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state mpd.socket >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask mpd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled mpd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable mpd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state mpd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
# In case this system is running systemd, we need to ensure that all
# necessary tmpfiles (if any) are created before starting.
if [ -d /run/systemd/system ] ; then
	systemd-tmpfiles --create /usr/lib/tmpfiles.d/mpd.conf >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/mpd" ]; then
	update-rc.d mpd defaults >/dev/null
	invoke-rc.d mpd start || exit $?
fi
# End automatically added section

