#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
	# clean up all statoverrides that belonged to mpd, so the
	# mpd system user can be removed cleanly
	for i in $(dpkg-statoverride --list | awk '/^mpd / {print $4}'); do
		if dpkg-statoverride --list --quiet "$i" >/dev/null; then
			dpkg-statoverride --force --quiet --remove "$i"
		fi
	done

        deluser --quiet --system mpd > /dev/null || true

	rm -rf /var/log/mpd /var/run/mpd/pid /var/lib/mpd/state \
            /var/lib/mpd/tag_cache > /dev/null 2>&1
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d mpd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask mpd.socket mpd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge mpd.socket mpd.service >/dev/null
		deb-systemd-helper unmask mpd.socket mpd.service >/dev/null
	fi
fi
# End automatically added section

